### ISSUE TITLE
Off-Command doesn't stop noise...

### ISSUE THREAD

**Issue by phedoff** [JKnipperts/TNDY-Tracker#2]
...but does in the provided tune (popcorn.tnd)?

Nevertheless a nice tracker, thanks for your effort.
By the way: is there a way to switch between periodic and white noise or do you have to change every "p" manually to "w"? Didn't find a key combo in the docs.

Regards

Update:
solved it: move cursor to last position and hit "f" (silence) - won't be visible. 
![202109184218_192742](https://user-images.githubusercontent.com/33154602/133897366-f1d515bf-3048-471c-897f-0e4027e9be52.png)

**Comment by JKnipperts** [comment]
Thanks for your feedback on my program.
I will check the off-command in the noise channel again. 

And of course you don't have to manually change the "p" to "w" every time you enter a noise value. You can use Shift+Page up or Shift+Page down to switch between periodic and white noise when editing. In the other channels you change with this combo the octave you want to use and in the noise channel the type of noise. I must have forgotten this when writing the help/instructions.... Will be added soon.

**Comment by phedoff** [comment]
Thanks. Also for the included description of the file format. Do you have plans to add an auto step feature (when entering notes)?
